export type InvoicePdfPartyDetails = {
  companyName?: string;
  loginEmail?: string;
  gstin?: string;
  cinRegistrationNumber?: string;
  address?: string;
  invoiceEmail?: string;
  billingSameAsCompany?: boolean;
  billingAddress?: string;
};

export type InvoicePdfLineItem = {
  serviceName?: string;
  currency?: string;
  price?: number;
};

export type InvoicePdfCurrencyTotal = {
  currency?: string;
  subtotal?: number;
};

export type InvoicePdfPayload = {
  invoiceNumber: string;
  createdAt: string;
  generatedByName: string;
  enterpriseDetails: InvoicePdfPartyDetails;
  clusoDetails: InvoicePdfPartyDetails;
  lineItems: InvoicePdfLineItem[];
  totalsByCurrency: InvoicePdfCurrencyTotal[];
};

function asRecord(value: unknown) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {} as Record<string, unknown>;
  }

  return value as Record<string, unknown>;
}

function asString(value: unknown, fallback = "") {
  if (typeof value !== "string") {
    return fallback;
  }

  return value;
}

function asNumber(value: unknown, fallback = 0) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) {
    return fallback;
  }

  return numeric;
}

export function toInvoicePdfPayload(value: unknown): InvoicePdfPayload {
  const raw = asRecord(value);

  const lineItemsRaw = Array.isArray(raw.lineItems) ? raw.lineItems : [];
  const totalsRaw = Array.isArray(raw.totalsByCurrency) ? raw.totalsByCurrency : [];

  return {
    invoiceNumber: asString(raw.invoiceNumber, "INV"),
    createdAt: asString(raw.createdAt),
    generatedByName: asString(raw.generatedByName),
    enterpriseDetails: asRecord(raw.enterpriseDetails) as InvoicePdfPartyDetails,
    clusoDetails: asRecord(raw.clusoDetails) as InvoicePdfPartyDetails,
    lineItems: lineItemsRaw.map((entry) => asRecord(entry) as InvoicePdfLineItem),
    totalsByCurrency: totalsRaw.map((entry) => asRecord(entry) as InvoicePdfCurrencyTotal),
  };
}

function formatDateTime(value: string) {
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return "-";
  }

  return parsed.toLocaleString("en-IN", {
    day: "numeric",
    month: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });
}

function formatMoney(amount: number, currency: string) {
  try {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(amount);
  } catch {
    return `${currency} ${amount.toFixed(2)}`;
  }
}

function sanitizePdfText(value: string) {
  return value.replace(/₹/g, "INR ").replace(/[^\u0009\u000A\u000D\u0020-\u00FF]/g, "");
}

export async function buildInvoicePdf(payload: InvoicePdfPayload): Promise<Buffer> {
  const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const width = page.getWidth();
  const height = page.getHeight();
  const margin = 30;
  const contentWidth = width - margin * 2;

  page.drawRectangle({
    x: 16,
    y: 16,
    width: width - 32,
    height: height - 32,
    borderColor: rgb(0.56, 0.08, 0.15),
    borderWidth: 2,
  });

  page.drawText(sanitizePdfText("Invoice"), {
    x: margin,
    y: height - 72,
    size: 32,
    font: boldFont,
    color: rgb(0.12, 0.27, 0.59),
  });

  page.drawText(sanitizePdfText(`Invoice #: ${payload.invoiceNumber}`), {
    x: margin,
    y: height - 96,
    size: 11,
    font: boldFont,
    color: rgb(0.23, 0.23, 0.23),
  });

  page.drawText(sanitizePdfText(`Generated: ${formatDateTime(payload.createdAt)}`), {
    x: margin,
    y: height - 112,
    size: 10,
    font,
    color: rgb(0.32, 0.32, 0.32),
  });

  if (payload.generatedByName.trim()) {
    page.drawText(sanitizePdfText(`Generated By: ${payload.generatedByName}`), {
      x: margin,
      y: height - 126,
      size: 10,
      font,
      color: rgb(0.32, 0.32, 0.32),
    });
  }

  const sectionTopY = height - 166;
  const colGap = 14;
  const colWidth = (contentWidth - colGap) / 2;
  const lineHeight = 13;

  const drawPartySection = (
    sectionTitle: string,
    details: InvoicePdfPartyDetails,
    x: number,
    y: number,
  ) => {
    page.drawRectangle({
      x,
      y: y - 186,
      width: colWidth,
      height: 186,
      borderColor: rgb(0.82, 0.82, 0.82),
      borderWidth: 1,
      color: rgb(0.98, 0.98, 0.98),
    });

    page.drawText(sanitizePdfText(sectionTitle), {
      x: x + 8,
      y: y - 16,
      size: 11,
      font: boldFont,
      color: rgb(0.12, 0.27, 0.59),
    });

    const lines = [
      `Company Name: ${details.companyName || "-"}`,
      `Login Email: ${details.loginEmail || "-"}`,
      `GSTIN: ${details.gstin || "-"}`,
      `CIN / Registration: ${details.cinRegistrationNumber || "-"}`,
      `Address: ${details.address || "-"}`,
      `Invoice Email: ${details.invoiceEmail || "-"}`,
      `Billing same as company: ${details.billingSameAsCompany ? "Yes" : "No"}`,
      `Billing Address: ${details.billingAddress || "-"}`,
    ];

    let lineY = y - 34;
    for (const line of lines) {
      page.drawText(sanitizePdfText(line), {
        x: x + 8,
        y: lineY,
        size: 9,
        font,
        color: rgb(0.15, 0.15, 0.15),
        maxWidth: colWidth - 14,
        lineHeight,
      });
      lineY -= 20;
    }
  };

  drawPartySection(
    "Customer details - Enterprise details",
    payload.enterpriseDetails,
    margin,
    sectionTopY,
  );
  drawPartySection("Cluso Infolink details", payload.clusoDetails, margin + colWidth + colGap, sectionTopY);

  const tableTopY = sectionTopY - 218;
  page.drawText(sanitizePdfText("Invoice Items (Latest Rates)"), {
    x: margin,
    y: tableTopY,
    size: 13,
    font: boldFont,
    color: rgb(0.12, 0.27, 0.59),
  });

  const tableHeaderY = tableTopY - 18;
  const colServiceX = margin;
  const colCurrencyX = margin + 300;
  const colRateX = margin + 390;

  page.drawLine({
    start: { x: margin, y: tableHeaderY + 11 },
    end: { x: margin + contentWidth, y: tableHeaderY + 11 },
    thickness: 1,
    color: rgb(0.15, 0.15, 0.15),
  });

  page.drawText("Service", {
    x: colServiceX,
    y: tableHeaderY,
    size: 10,
    font: boldFont,
    color: rgb(0.15, 0.15, 0.15),
  });
  page.drawText("Currency", {
    x: colCurrencyX,
    y: tableHeaderY,
    size: 10,
    font: boldFont,
    color: rgb(0.15, 0.15, 0.15),
  });
  page.drawText("Rate", {
    x: colRateX,
    y: tableHeaderY,
    size: 10,
    font: boldFont,
    color: rgb(0.15, 0.15, 0.15),
  });

  let rowY = tableHeaderY - 16;
  for (const item of payload.lineItems) {
    page.drawText(sanitizePdfText(item.serviceName || "-"), {
      x: colServiceX,
      y: rowY,
      size: 9,
      font,
      color: rgb(0.18, 0.18, 0.18),
      maxWidth: 290,
      lineHeight: 11,
    });
    page.drawText(sanitizePdfText(asString(item.currency, "INR")), {
      x: colCurrencyX,
      y: rowY,
      size: 9,
      font,
      color: rgb(0.18, 0.18, 0.18),
    });
    page.drawText(
      sanitizePdfText(formatMoney(asNumber(item.price, 0), asString(item.currency, "INR"))),
      {
        x: colRateX,
        y: rowY,
        size: 9,
        font: boldFont,
        color: rgb(0.12, 0.12, 0.12),
      },
    );

    rowY -= 16;
    page.drawLine({
      start: { x: margin, y: rowY + 4 },
      end: { x: margin + contentWidth, y: rowY + 4 },
      thickness: 0.6,
      color: rgb(0.65, 0.65, 0.65),
    });
  }

  rowY -= 8;
  for (const total of payload.totalsByCurrency) {
    const text = `Total (${asString(total.currency, "INR")}): ${formatMoney(
      asNumber(total.subtotal, 0),
      asString(total.currency, "INR"),
    )}`;
    page.drawText(sanitizePdfText(text), {
      x: margin,
      y: rowY,
      size: 10,
      font: boldFont,
      color: rgb(0.12, 0.12, 0.12),
    });
    rowY -= 14;
  }

  return Buffer.from(await pdfDoc.save());
}
